run:
    skip-dirs:
        - (^|/)pb($|/)
        - (^|/)thrift($|/)

    timeout: 2m

linters-settings:
    golint:
        min-confidence: 0.9
    goimports:
        local-prefixes: github.com/go-kit/kit

linters:
    disable-all: true
    enable:
        - govet
        #- golint
        #- gofmt
        #- staticcheck

service:
    golangci-lint-version: 1.23.x
