version: 2

jobs:
  test:
    docker:
      - image: circleci/golang:1.11beta3
    working_directory: /go/src/github.com/go-kit/kit
    environment:
      ETCD_ADDR: http://localhost:2379
      CONSUL_ADDR: localhost:8500
      ZK_ADDR: localhost:2181
      EUREKA_ADDR: http://localhost:8761/eureka     
    steps:
      - checkout
      - setup_remote_docker
      - run: docker-compose -f docker-compose-integration.yml up -d --force-recreate
      - run: go get -t github.com/go-kit/kit/...
      - run: go test -v -race -tags integration github.com/go-kit/kit/...
